#!/usr/bin/env bats
#
# mode_loop_extend.bats — integration tests for make-video loop-extend mode (PRD-2)
#
# Contract (when input is a single video clip):
#   make-video CLIP HOURS [--loop crossfade|pingpong|native] [--xfade SECS] [--yes]
#              [--audio PATH] [--out OUTDIR]
#
# Triggered by: classify_input(CLIP) == "video"
# Default loop strategy: crossfade
# Default xfade: 1.0
# Preview gate:  seam_check at wrap boundary; prints verdict + recommendation;
#                only prompts stdin when -t 0 (TTY); in non-TTY context proceeds
#                automatically (no hang).
# Duration:      output ≈ target ± 1.0 s
#
# Test durations: HOURS=0.005 → 18 s   (fast; well within ffmpeg tolerance)
#                 HOURS=0.006 → ~22 s
#                 HOURS=0.004 → ~14 s
#
# Clips are generated by mk_clip (gradients, 320x180, 30fps, ~3 s) so they
# are short enough that loop-extend must tile ≥3 times to reach 18 s.

REPO_ROOT="$(cd "$(dirname "$BATS_TEST_FILENAME")/.." && pwd)"

bats_require_minimum_version 1.5.0

setup() {
  load "$REPO_ROOT/tests/helpers/fixtures.sh"
  load "$REPO_ROOT/tests/helpers/assert.sh"
  WORK_DIR="$(mktemp -d)"
}

teardown() {
  rm -rf "$WORK_DIR"
}

# ---------------------------------------------------------------------------
# Test 1 — basic loop-extend: clip + short duration, default (crossfade) loop.
#
# Contract:
#   - exits 0
#   - output has a video stream
#   - output duration ≈ target ± 1.0 s
#   - does NOT hang in non-TTY context (regression guard)
#
# stdin in bats is not a TTY, so the preview gate must auto-proceed.
# Passing --yes makes the intent explicit and also serves as the no-hang guard.
# ---------------------------------------------------------------------------

@test "loop-extend default crossfade: output duration ≈ target, has video stream" {
  local clip="$WORK_DIR/src.mp4"
  local out="$WORK_DIR/src.mp4"  # out_path derives stem from CLIP basename

  mk_clip "$clip" 440 3

  run "$REPO_ROOT/make-video" "$clip" 0.005 --yes --out "$WORK_DIR"
  [ "$status" -eq 0 ]
  [ -f "$out" ]

  assert_has_stream "$out" v
  # target = round(0.005 * 3600) = 18 s; allow ±1.0 s
  assert_duration "$out" 18 1.0
}

# ---------------------------------------------------------------------------
# Test 2 — pingpong strategy: wrap boundary passes assert_seam_ok.
#
# The pingpong unit is forward+reverse so both the internal turn AND the wrap
# are truly seamless.  We concatenate the unit twice, then check the boundary
# frame between the two copies.
#
# We don't invoke make-video here; we test via loop_unit + manual concat so
# we can exercise the seam precisely.  This is an in-process integration test
# of the loop building block that make-video loop-extend relies on.
# ---------------------------------------------------------------------------

@test "loop-extend --loop pingpong: wrap boundary passes seam check (SEAMLESS)" {
  local clip="$WORK_DIR/src.mp4"
  local unit="$WORK_DIR/unit.mp4"
  local tiled="$WORK_DIR/tiled.mp4"
  mk_clip "$clip" 440 4

  source "$REPO_ROOT/lib/loop.sh"

  loop_unit "$clip" "$unit" --loop pingpong

  # Tile 2 copies of the unit to expose the wrap boundary
  local list="$WORK_DIR/concat.txt"
  printf "file '%s'\n" "$unit" > "$list"
  printf "file '%s'\n" "$unit" >> "$list"
  "$FFMPEG" -nostdin -loglevel error -y -f concat -safe 0 -i "$list" -c copy "$tiled"

  # The boundary frame is at frame = unit_duration_frames
  local unit_frames
  unit_frames="$("$FFPROBE" -v error \
    -select_streams v:0 \
    -count_packets \
    -show_entries stream=nb_read_packets \
    -of default=noprint_wrappers=1:nokey=1 \
    "$unit")"
  [[ "$unit_frames" =~ ^[0-9]+$ ]]

  # boundary_frame = first frame of the second copy (1-based, so = unit_frames + 1
  # but assert_seam_ok uses 0-based FRAME which is the boundary_b frame index).
  # assert_seam_ok takes the FIRST frame of the second copy (0-based), i.e. unit_frames.
  assert_seam_ok "$tiled" "$unit_frames"
}

# ---------------------------------------------------------------------------
# Test 3 — preview gate verdict appears in stdout; recommendation fires for
# non-SEAMLESS crossfade output.
#
# We run loop-extend with default crossfade (which produces SOFT/VISIBLE on
# directional motion content) and capture stdout.  The verdict line must
# appear.  If the verdict is NOT SEAMLESS, the pingpong recommendation must
# also appear.
# ---------------------------------------------------------------------------

@test "loop-extend: preview gate prints verdict; non-SEAMLESS triggers pingpong tip" {
  local clip="$WORK_DIR/src.mp4"
  local out="$WORK_DIR/src.mp4"
  mk_clip "$clip" 440 3

  run "$REPO_ROOT/make-video" "$clip" 0.005 --yes --out "$WORK_DIR"
  [ "$status" -eq 0 ]

  # stdout must contain a seam verdict line
  echo "$output" | grep -qE "(SEAMLESS|SOFT|VISIBLE)"

  # Determine the actual verdict
  local verdict
  verdict="$(echo "$output" | grep -oE '(SEAMLESS|SOFT|VISIBLE)' | head -1)"

  if [[ "$verdict" != "SEAMLESS" ]]; then
    # Non-SEAMLESS crossfade output → must print pingpong recommendation
    echo "$output" | grep -qi "pingpong"
  fi
}

# ---------------------------------------------------------------------------
# Test 4 — --audio FILE: output has audio stream; duration ≈ target.
#
# When --audio is provided in loop-extend mode, the audio_build + mux_audio
# PRD-5 path is reused.
# ---------------------------------------------------------------------------

@test "loop-extend --audio FILE: output has audio stream; duration ≈ target" {
  local clip="$WORK_DIR/src.mp4"
  local audio="$WORK_DIR/tone.aac"
  local out="$WORK_DIR/src.mp4"
  mk_clip "$clip" 440 3
  mk_audio "$audio" 330 5

  run "$REPO_ROOT/make-video" "$clip" 0.005 --yes --audio "$audio" --out "$WORK_DIR"
  [ "$status" -eq 0 ]
  [ -f "$out" ]

  assert_has_stream "$out" v
  assert_has_stream "$out" a
  assert_duration "$out" 18 1.0
}

# ---------------------------------------------------------------------------
# Test 5 — native audio preserved: clip WITH audio, no --audio flag.
#
# loop_unit crossfade (default) loops the clip's audio through the unit.
# The final output should preserve audio because the clip has it.
# ---------------------------------------------------------------------------

@test "loop-extend (no --audio): native clip audio preserved in output" {
  local clip="$WORK_DIR/src.mp4"
  local out="$WORK_DIR/src.mp4"
  mk_clip "$clip" 440 3   # mk_clip produces audio+video

  run "$REPO_ROOT/make-video" "$clip" 0.005 --yes --out "$WORK_DIR"
  [ "$status" -eq 0 ]
  [ -f "$out" ]

  assert_has_stream "$out" v
  assert_has_stream "$out" a
}

# ---------------------------------------------------------------------------
# Test 6 — no-hang regression guard: loop-extend MUST complete in non-TTY.
#
# Explicitly pass --yes (auto-confirm); also rely on bats stdin not being a TTY.
# We set a tight timeout via a background subshell to catch any accidental
# interactive prompt.
# ---------------------------------------------------------------------------

@test "loop-extend: completes without hanging in non-TTY context (--yes)" {
  local clip="$WORK_DIR/src.mp4"
  local out="$WORK_DIR/src.mp4"
  mk_clip "$clip" 440 3

  # Run with a 120-second hard timeout so the test suite can't hang forever.
  # bats `run` is fine here; the --yes flag is the actual regression guard.
  run "$REPO_ROOT/make-video" "$clip" 0.005 --yes --out "$WORK_DIR"
  [ "$status" -eq 0 ]
  [ -f "$out" ]
}

# ---------------------------------------------------------------------------
# Test 7 — temp cleanup on failure.
#
# Strategy: supply a zero-byte --audio file that exists (passes -e check)
# but will fail audio_build after the loop unit is already built.
# Assert no orphaned temp dirs in the system tmp area.
# ---------------------------------------------------------------------------

@test "loop-extend --audio (failure): no orphaned temp dir after mid-pipeline failure" {
  local clip="$WORK_DIR/src.mp4"
  local bad_audio="$WORK_DIR/bad.aac"
  mk_clip "$clip" 440 3
  touch "$bad_audio"   # exists but empty → audio_build returns non-zero

  # Snapshot ALL tmp.* entries in TMPDIR before the run (stronger than checking
  # one specific filename — catches any mktemp-created dir that leaks).
  local tmpbase="${TMPDIR:-/tmp}"
  # Strip trailing slash for consistent path construction
  tmpbase="${tmpbase%/}"

  local before_dirs
  before_dirs="$(find "$tmpbase" -maxdepth 1 -name 'tmp.*' -type d 2>/dev/null | sort)"

  run "$REPO_ROOT/make-video" "$clip" 0.005 --yes --audio "$bad_audio" --out "$WORK_DIR"
  [ "$status" -ne 0 ]

  local after_dirs
  after_dirs="$(find "$tmpbase" -maxdepth 1 -name 'tmp.*' -type d 2>/dev/null | sort)"

  # No new tmp.* dirs should have appeared
  [ "$before_dirs" = "$after_dirs" ]
}

# ---------------------------------------------------------------------------
# Test 8 — REGRESSION: preview gate reports SEAMLESS for pingpong output.
#
# This test exists to catch the frame-index off-by-one bug where
# unit_frames was computed from duration*fps (floating point, off by ±1)
# instead of the actual packet count.  The wrong frame pointed mid-clip-2
# rather than at the wrap, making the gate report SOFT even for a truly
# seamless pingpong loop.
#
# Contract: make-video --loop pingpong --yes prints "SEAMLESS" in the
# preview gate output, matching the real seam quality that test 2 proves.
# ---------------------------------------------------------------------------

@test "loop-extend --loop pingpong: preview gate reports SEAMLESS verdict" {
  local clip="$WORK_DIR/src.mp4"
  local out="$WORK_DIR/src.mp4"
  # Use a 4-second clip so the unit has enough frames for seam_check (>=12)
  mk_clip "$clip" 440 4

  run "$REPO_ROOT/make-video" "$clip" 0.005 --loop pingpong --yes --out "$WORK_DIR"
  [ "$status" -eq 0 ]

  # The preview gate MUST print "SEAMLESS" for pingpong (the actual seam is seamless)
  echo "$output" | grep -q "SEAMLESS"
}

# ---------------------------------------------------------------------------
# Test 9 — --zoom on a video input must be rejected with a clear error.
#
# --zoom is a still-image-mode flag (it drives the zoompan filter on images).
# Silently ignoring it in loop-extend mode would confuse operators who expect
# Ken Burns motion.  We require a die() with a helpful message instead.
# ---------------------------------------------------------------------------

@test "loop-extend: --zoom on a video input fails with clear error" {
  local clip="$WORK_DIR/src.mp4"
  mk_clip "$clip" 440 3

  run "$REPO_ROOT/make-video" "$clip" 0.005 --zoom 4 --yes --out "$WORK_DIR"
  [ "$status" -ne 0 ]
  echo "$output" | grep -qi "zoom"
}

# ---------------------------------------------------------------------------
# Test 10 — invalid --loop value rejected at flag-parse time.
#
# loop_unit would error eventually, but a clean rejection at argument parse
# time gives a more useful error message than an ffmpeg failure deep inside.
# ---------------------------------------------------------------------------

@test "loop-extend: invalid --loop value rejected with clear error" {
  local clip="$WORK_DIR/src.mp4"
  mk_clip "$clip" 440 3

  run "$REPO_ROOT/make-video" "$clip" 0.005 --loop bogus --yes --out "$WORK_DIR"
  [ "$status" -ne 0 ]
  echo "$output" | grep -qi "loop"
}
