#!/usr/bin/env bats
#
# mode_slideshow.bats — integration tests for make-video slideshow mode (PRD-1)
#
# Contract (when input is a directory + --slideshow):
#   make-video DIR --slideshow [--each HOURS] [--xfade SECS] [--shuffle]
#              [--fill] [--audio PATH] [--out OUTDIR] [--yes]
#
# Triggered by: DIR input + SLIDESHOW=1
# Default each: positional HOURS (required)
# Default xfade: 2.5 s
# Duration formula: total_secs = Σ(each_i) − (n−1)·xfade
#
# Test durations: --each 0.002h → 7.2s per image (fast renders)
#                 --xfade 1.0 → 1.0s dissolves
#
# Images are generated by mk_image (solid colors: red, green, blue).
# Distinct colors make dissolves measurable.

REPO_ROOT="$(cd "$(dirname "$BATS_TEST_FILENAME")/.." && pwd)"

bats_require_minimum_version 1.5.0

setup() {
  load "$REPO_ROOT/tests/helpers/fixtures.sh"
  load "$REPO_ROOT/tests/helpers/assert.sh"
  WORK_DIR="$(mktemp -d)"
}

teardown() {
  rm -rf "$WORK_DIR"
}

# ---------------------------------------------------------------------------
# Helper: mk_slide_dir DIR COLOR [COLOR2 ...]
#
# Create a directory at DIR with one PNG per COLOR argument.
# Files named 01_red.png, 02_green.png, etc.  No argument = 3 default colors.
# ---------------------------------------------------------------------------
mk_slide_dir() {
  local dir="${1:?mk_slide_dir: DIR required}"; shift
  mkdir -p "$dir"
  local colors=("$@")
  [[ "${#colors[@]}" -gt 0 ]] || colors=(red green blue)
  local i=1
  for color in "${colors[@]}"; do
    mk_image "$dir/$(printf '%02d' "$i")_${color}.png" "$color"
    (( i++ )) || true
  done
}

# ---------------------------------------------------------------------------
# Test 1 — duration math
#
# 3 images × each=0.002h (7.2s each), xfade=1.0s
# total = 3×7.2 − 2×1.0 = 21.6 − 2.0 = 19.6s
#
# Contract:
#   - exits 0
#   - output duration ≈ 19.6 ± 0.5 s
#   - output has exactly one video stream
# ---------------------------------------------------------------------------

@test "slideshow: 3-image duration math (3×7.2 − 2×1.0 = 19.6s)" {
  local dir="$WORK_DIR/imgs"
  local out="$WORK_DIR/out.mp4"
  mk_slide_dir "$dir" red green blue

  run "$REPO_ROOT/make-video" "$dir" 0.002 --slideshow --xfade 1.0 --out "$out"
  [ "$status" -eq 0 ]
  [ -f "$out" ]

  assert_has_stream "$out" v
  # 3 × 7.2 − 2 × 1.0 = 19.6 s
  assert_duration "$out" 19.6 0.5
}

# ---------------------------------------------------------------------------
# Test 2 — dissolve is NOT a hard cut (with hard-cut negative control)
#
# Part A (POSITIVE): build a 2-image slideshow (red → green) with xfade 1.0s.
#   At the dissolve midpoint frame, the baseline pair is ALSO inside the dissolve
#   so both baseline and boundary PSNR are ~40 dB → drop ≈ 0 → SEAMLESS.
#   assert_seam_ok PASSES, proving adjacent frames blend gradually.
#
# Part B (NEGATIVE CONTROL): hard-concat the same two solid-color stills
#   with NO xfade. At the cut frame, the baseline pair is inside solid red
#   (PSNR=999/inf) while the boundary pair crosses the cut (PSNR≈12 dB).
#   Drop ≈ 987 dB >> 8 dB threshold → assert_seam_ok FAILS.
#   This proves the seam check actually measures something real.
#
# Frame math (each=0.002h=7.2s, xfade=1.0s, fps=30):
#   hold_0 = 7.2 − 1.0 = 6.2s → 186 frames (0-based: 0..185)
#   dissolve = 1.0s → 30 frames (0-based: 186..215)
#   dissolve midpoint ≈ 0-based frame 201 → seam_ok param = 202
#   (at frame 202, baseline pair lands at 0-based 190-191 = inside dissolve,
#    baseline PSNR ≈ boundary PSNR ≈ 40 dB → SEAMLESS)
#
#   Hard cut: 6s red segment → 180 frames (0-based: 0..179)
#   Cut at 0-based frame 180 → seam_ok param = 180
#   (baseline pair at 0-based 168-169 = solid red PSNR=999,
#    boundary pair at 0-based 179-180 crosses cut PSNR≈12 dB → FAIL)
# ---------------------------------------------------------------------------

@test "slideshow: dissolve is NOT a hard cut (positive + hard-cut negative control)" {
  local img_dir="$WORK_DIR/imgs"
  local out_dissolve="$WORK_DIR/dissolve.mp4"
  local out_hardcut="$WORK_DIR/hardcut.mp4"
  mk_slide_dir "$img_dir" red green

  # --- Part A: slideshow with dissolve ---
  run "$REPO_ROOT/make-video" "$img_dir" 0.002 --slideshow --xfade 1.0 --out "$out_dissolve"
  [ "$status" -eq 0 ]
  [ -f "$out_dissolve" ]

  # Frame 202 (1-based param): baseline pair 190-191 and boundary pair 201-202
  # are both inside the dissolve → both ~40 dB → drop ≈ 0 → SEAMLESS (PASS).
  assert_seam_ok "$out_dissolve" 202

  # --- Part B: hard-cut negative control ---
  # Build two 6-second solid-color stills, concat with NO xfade.
  local img_red="$WORK_DIR/red.png"
  local img_green="$WORK_DIR/green.png"
  mk_image "$img_red" red
  mk_image "$img_green" green

  local hold_red="$WORK_DIR/hold_red.mp4"
  local hold_green="$WORK_DIR/hold_green.mp4"
  "$FFMPEG" -nostdin -loglevel error -y \
    -loop 1 -framerate 30 -t 6 -i "$img_red" \
    -vf "scale=320:180,format=yuv420p" \
    -c:v libx264 -preset ultrafast -crf 23 -an "$hold_red"
  "$FFMPEG" -nostdin -loglevel error -y \
    -loop 1 -framerate 30 -t 6 -i "$img_green" \
    -vf "scale=320:180,format=yuv420p" \
    -c:v libx264 -preset ultrafast -crf 23 -an "$hold_green"

  local list_hc="$WORK_DIR/list_hc.txt"
  printf "file '%s'\n" "$hold_red" > "$list_hc"
  printf "file '%s'\n" "$hold_green" >> "$list_hc"
  "$FFMPEG" -nostdin -loglevel error -y \
    -f concat -safe 0 -i "$list_hc" -c copy "$out_hardcut"

  # Frame 180 (1-based param): boundary pair crosses cut (PSNR≈12 dB),
  # baseline pair is inside solid red (PSNR=999 dB) → drop≈987 → FAILS.
  # Use "run" to capture failure without aborting the test.
  run assert_seam_ok "$out_hardcut" 180
  # Negative control: assert_seam_ok MUST FAIL on the hard cut
  [ "$status" -ne 0 ]
}

# ---------------------------------------------------------------------------
# Test 3 — single image degenerates (no transition subtracted)
#
# A 1-image folder + --slideshow:
#   - exits 0
#   - output has one video stream
#   - duration ≈ each (7.2s) with NO xfade subtraction
# ---------------------------------------------------------------------------

@test "slideshow: single-image folder degenerates (no transition, full duration)" {
  local dir="$WORK_DIR/single"
  local out="$WORK_DIR/single_out.mp4"
  mkdir -p "$dir"
  mk_image "$dir/01_blue.png" blue

  run "$REPO_ROOT/make-video" "$dir" 0.002 --slideshow --xfade 1.0 --out "$out"
  [ "$status" -eq 0 ]
  [ -f "$out" ]

  assert_has_stream "$out" v
  # 1 image, no transitions: total = 1 × 7.2 = 7.2s (no subtraction)
  assert_duration "$out" 7.2 0.5
}

# ---------------------------------------------------------------------------
# Test 4 — junk files are skipped
#
# A folder with:
#   - 2 real PNGs
#   - 1 AppleDouble ._foo.jpg file
#   - 1 .txt file
#
# Only 2 real images should be counted.
# total = 2 × 7.2 − 1 × 1.0 = 13.4s (not 3 × 7.2 − 2 × 1.0 = 19.6s)
# ---------------------------------------------------------------------------

@test "slideshow: skips ._* AppleDouble and non-image files" {
  local dir="$WORK_DIR/junk"
  mkdir -p "$dir"
  mk_image "$dir/01_red.png" red
  mk_image "$dir/02_blue.png" blue
  # Create junk: AppleDouble sidecar
  touch "$dir/._foo.jpg"
  # Create junk: non-image file
  echo "not an image" > "$dir/notes.txt"

  local out="$WORK_DIR/junk_out.mp4"
  run "$REPO_ROOT/make-video" "$dir" 0.002 --slideshow --xfade 1.0 --out "$out"
  [ "$status" -eq 0 ]
  [ -f "$out" ]

  assert_has_stream "$out" v
  # 2 real images: 2 × 7.2 − 1 × 1.0 = 13.4s
  # If junk were counted (3 images): 3 × 7.2 − 2 × 1.0 = 19.6s — wrong
  assert_duration "$out" 13.4 0.5
}

# ---------------------------------------------------------------------------
# Test 5 — audio path
#
# 2-image slideshow + --audio FILE:
#   - exits 0
#   - output has both video and audio streams
#   - output duration ≈ total_secs = 2 × 7.2 − 1 × 1.0 = 13.4s
# ---------------------------------------------------------------------------

@test "slideshow: --audio FILE → output has audio stream at correct duration" {
  local dir="$WORK_DIR/audio_imgs"
  local audio_file="$WORK_DIR/tone.aac"
  local out="$WORK_DIR/audio_out.mp4"
  mk_slide_dir "$dir" red blue
  mk_audio "$audio_file" 440 5

  run "$REPO_ROOT/make-video" "$dir" 0.002 --slideshow --xfade 1.0 \
    --audio "$audio_file" --out "$out"
  [ "$status" -eq 0 ]
  [ -f "$out" ]

  assert_has_stream "$out" v
  assert_has_stream "$out" a
  # 2 × 7.2 − 1 × 1.0 = 13.4s
  assert_duration "$out" 13.4 0.5
}

# ---------------------------------------------------------------------------
# Test 6 — --slideshow on a single file must fail with clear error
#
# The spec says: "Reject nonsense combos cleanly with die (e.g. --slideshow
# on a single file)."
# ---------------------------------------------------------------------------

@test "slideshow: --slideshow on a single image file fails with clear error" {
  local img="$WORK_DIR/solo.png"
  mk_image "$img" red

  run "$REPO_ROOT/make-video" "$img" 0.002 --slideshow --out "$WORK_DIR"
  [ "$status" -ne 0 ]
  echo "$output" | grep -qiE "(slideshow|directory|dir)"
}

# ---------------------------------------------------------------------------
# Test 7 — --zoom with --slideshow must fail with clear error
#
# --zoom is a still-image single-file mode feature; combining it with
# --slideshow is meaningless and must be rejected early.
# ---------------------------------------------------------------------------

@test "slideshow: --zoom with --slideshow fails with clear error" {
  local dir="$WORK_DIR/zoom_imgs"
  mk_slide_dir "$dir" red blue

  run "$REPO_ROOT/make-video" "$dir" 0.002 --slideshow --zoom 4 --out "$WORK_DIR"
  [ "$status" -ne 0 ]
  echo "$output" | grep -qiE "(zoom|slideshow)"
}

# ---------------------------------------------------------------------------
# Test 8 — --each alias for per-image hold (positional HOURS still works)
#
# When --each is passed, it controls the per-image hold duration.
# 2 images × each=0.002h (7.2s), xfade=1.0s → total = 13.4s
# ---------------------------------------------------------------------------

@test "slideshow: --each flag sets per-image hold duration" {
  local dir="$WORK_DIR/each_imgs"
  local out="$WORK_DIR/each_out.mp4"
  mk_slide_dir "$dir" red blue

  # Use --each instead of positional HOURS
  run "$REPO_ROOT/make-video" "$dir" --slideshow --each 0.002 --xfade 1.0 --out "$out"
  [ "$status" -eq 0 ]
  [ -f "$out" ]

  assert_has_stream "$out" v
  # 2 × 7.2 − 1 × 1.0 = 13.4s
  assert_duration "$out" 13.4 0.5
}

# ---------------------------------------------------------------------------
# Test 9 — long hold exercises the encode-once + concat-copy branch
#
# hold_i > BASE_SECS (30s) forces _slideshow_build_hold into the loop path:
#   encode ONE 30s base segment, concat-copy N times + fractional remainder.
# Without this test, a regression back to full-re-encode would silently pass
# the duration checks (output is still the right length, just built slowly).
#
# 2 images × each=0.011h (≈39.6s), xfade=1.0s → total ≈ 39.6×2 − 1.0 = 78.2s
# This is fast to measure (duration check only) but forces loops≥1 through
# the concat-copy path since 39.6 > BASE_SECS (30).
# ---------------------------------------------------------------------------

@test "slideshow: long hold (>30s) exercises encode-once + concat-copy path" {
  local dir="$WORK_DIR/long_imgs"
  local out="$WORK_DIR/long_out.mp4"
  mk_slide_dir "$dir" red blue

  # each=0.011h = 39.6s > BASE_SECS(30) → forces loops≥1 in _slideshow_build_hold
  run "$REPO_ROOT/make-video" "$dir" 0.011 --slideshow --xfade 1.0 --out "$out"
  [ "$status" -eq 0 ]
  [ -f "$out" ]

  assert_has_stream "$out" v
  # 2 × 39.6 − 1 × 1.0 = 78.2s
  assert_duration "$out" 78.2 0.5
}
